In [3]:
###### IMPORTING LIBRARY
import numpy as np
from numpy import*

In [8]:
####### Declaring array and datatype
arr=array([1])
print(arr)
print(arr.dtype)

[1]
int64


In [12]:
import numpy as np

a = np.array([1, 2, 3])
print(a.dtype)

b = np.array([100000])
print(b.dtype)

c = np.array([9999999999])
print(c.dtype)

int64
int64
int64


In [13]:
arr=array([5,7,8.8,9.0])
print(arr)

[5.  7.  8.8 9. ]


In [14]:
print(arr.dtype)

float64


In [16]:
arr=array([True,False])
print(arr.dtype)

bool


In [17]:
arr=array([1,32.6,55.4],float)
print(arr)
print(arr.dtype)

[ 1.  32.6 55.4]
float64


In [18]:
arr=array([1,32.6,55.4],int)
print(arr)
print(arr.dtype)

[ 1 32 55]
int64


In [21]:
#### linspace
arr=linspace(1,100,10)
print(arr)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [115]:
##### arange
arr=np.arange(1,6)
print(arr)

[1 2 3 4 5]


In [25]:
arr=np.arange(2,21,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [26]:
arr=np.arange(1,22,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [27]:
#### logarthmic values
arr=logspace(1,33,8)
print(arr)

[1.00000000e+01 3.72759372e+05 1.38949549e+10 5.17947468e+14
 1.93069773e+19 7.19685673e+23 2.68269580e+28 1.00000000e+33]


In [28]:
print(arr[4])

1.9306977288832455e+19


In [38]:
arr=array([4,6,9,6])
print(arr[3])

6


In [45]:
print('%.3f' %arr[3])

6.000


In [46]:
arr=zeros(3,int)
print(arr)

[0 0 0]


In [47]:
arr=ones(3,float)
print(arr)

[1. 1. 1.]


In [48]:
arr=zeros(3,bool)
print(arr)

[False False False]


In [50]:
arr=ones(3,bool)
print(arr)

[ True  True  True]


In [51]:
print(arr.dtype)

bool


In [52]:
arr=zeros(3)
print(arr)

[0. 0. 0.]


In [55]:
arr= zeros((3,3),int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [56]:
arr= ones((3,3),float)
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [63]:
arr=ones((2,3,2),int)
print(arr)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [66]:
#### list
list=[1,6.6,"abi"]
arr=np.array(list)
print(arr)

['1' '6.6' 'abi']


In [67]:
list=[[1,2,3,4],[5,3,7,6]]
arr=np.array(list)
print(arr)

[[1 2 3 4]
 [5 3 7 6]]


In [69]:
list=[[1,2,3],[5,3,7],[8,9,6]]
arr=np.array(list)
print(arr)

[[1 2 3]
 [5 3 7]
 [8 9 6]]


In [70]:
matrix1=np.full(100,0)
print(matrix1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [71]:
matrix=np.full((3,3),5)
print(matrix)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [76]:
matrix=np.full((1,3,4),5)
print(matrix)

[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [77]:
##### identity matrix
matrix=np.eye(4,4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [78]:
#### diagonalize matrix
arr=np.diag([1,5])
print(arr)

[[1 0]
 [0 5]]


In [79]:
mat=np.diag([1,5,7,9,6])
print(mat)

[[1 0 0 0 0]
 [0 5 0 0 0]
 [0 0 7 0 0]
 [0 0 0 9 0]
 [0 0 0 0 6]]


In [81]:
###### Random number generation
arr= np.random.rand(3)
print(arr)

[0.20833039 0.86044644 0.47971999]


In [82]:
arr= np.random.rand(3,2)
print(arr)

[[0.71499723 0.9720251 ]
 [0.88675869 0.08895471]
 [0.58893428 0.65905457]]


In [84]:
arr= np.random.rand(2,2,3)
print(arr)

[[[0.94854064 0.80439774 0.82161465]
  [0.5175283  0.2598896  0.03148823]]

 [[0.79136569 0.16712157 0.63192432]
  [0.40710466 0.29790569 0.35221233]]]


In [91]:
### using randn combine both positive and negative
arr= np.random.randn(1,2,3)
print(arr)

[[[-0.67832785  0.6753756   0.05444144]
  [ 0.12135293 -0.60719288  0.63720736]]]


In [92]:
arr=np.random.randn(4,1,3)
print(arr)

[[[ 0.72034269 -0.83770179 -0.03763385]]

 [[-1.91673466  1.25778929  0.79087075]]

 [[ 0.9957385  -2.0107855  -1.61594339]]

 [[ 1.0622147  -0.31671649 -0.60522433]]]


In [93]:
arr=np.random.randint(0,10,10)
print(arr)

[3 0 4 8 5 0 9 0 1 9]


In [94]:
arr=np.random.randint(1,22,(4,4))
print(arr)

[[ 4 19 21  7]
 [19 14 19  9]
 [17 10 17 13]
 [ 8 10 18 17]]


In [101]:
arr=linspace(1,5,4)
print(arr)

[1.         2.33333333 3.66666667 5.        ]


In [100]:
arr.ndim

1

In [102]:
arr.shape

(4,)

In [103]:
arr.size

4

In [105]:
arr=ones([2,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [110]:
arr.ndim

2

In [111]:
arr.shape

(2, 3)

In [112]:
arr.size

6

In [113]:
arr.dtype

dtype('float64')